var language_ES = {
    labels: {/*etiquetas y placeholders*/
        forgot_pass: '¿Olvide mi contraseña?',
        btn_entrar: 'Entrar',
        copy_right: '&COPY; 2017 -  Perú. Todos los derechos reservados.',
        user: 'Usuario',
        pass: 'Contraseña',
        pass_new: 'Nueva Contraseña',
        buscar_menu: 'Buscar menú...',
        m_app: 'Aplicación',
        cambia_pass: 'Cambiar contraseña',
        out: 'Salir',
        search_menu: 'Buscar opcion',
        descripcion: 'Descripción',
        title_nmenu_new: 'Nuevo Menú',
        title_nmenu_edit: 'Editar Menú',
        activo: 'Activo',
        inactivo: 'Inactivo',
        btn_close: 'Cerrar',
        btn_agregar: 'Agregar',
        btn_limpiar: 'Limpiar',
        alias: 'Alias',
        ajax: 'Ajax',
        nombre: 'Nombre',
        estado: 'Estado',
        t_alias: 'Este alias se utilizará como prefijo para todos los elementos que serán contenidos en este menú, debe ser único en el sistema. Se permiten 10 caracteres como máximo.',
        t_ajax: `Evento que se ejecutara al dar click en la opción de menú. Ejm: Exe.require({system: 'Boton'},this);`,
        press_enter: 'Escriba y presione [Enter]',
        title_fase_new: 'Nueva Fase',
        title_fase_edit: 'Editar Fase',
        title_grupo_new: 'Nuevo Grupo',
        title_grupo_edit: 'Editar Grupo',
        title_tipoingreso_new: 'Nuevo Tipo de Ingreso',
        title_tipoingreso_edit: 'Editar Tipo de Ingreso',
        title_modalidadadmision_new: 'Nueva Modalidad de Admision',
        title_modalidadadmision_edit: 'Editar Modalidad de Admision',
        title_proceso_new: 'Nuevo Proceso',
        title_proceso_edit: 'Editar Proceso',
        title_semestre_new: 'Nuevo Semestre',
        title_semestre_edit: 'Editar Semestre',
        title_filial_new: 'Nueva Filial',
        title_filial_edit: 'Editar Filial',
        title_estadocivil_new: 'Nuevo Estado Civil',
        title_estadocivil_edit: 'Editar Estado Civil',
        title_tiposemestre_new: 'Nuevo Tipo de Semestre',
        title_tiposemestre_edit: 'Editar Tipo de Semestre',
        title_tipoambiente_new: 'Nuevo Tipo de Ambiente',
        title_tipoambiente_edit: 'Editar Tipo de Ambiente',
        title_ambiente_new: 'Nuevo Ambiente',
        title_ambiente_edit: 'Editar Ambiente',
        title_tipoestructura_new: 'Nuevo Tipo de Estructura',
        title_tipoestructura_edit: 'Editar Tipo de Estructura',
        title_estructura_new: 'Nueva Estructura',
        title_estructura_edit: 'Editar Estructura',
        title_pais_new: 'Nuevo Pais',
        title_pais_edit: 'Editar Pais',
        title_parametro_new: 'Nuevo Parametro',
        title_parametro_edit: 'Editar Parametro',
        title_seccionparametro_new: 'Nueva Seccion de Parametro',
        title_seccionparametro_edit: 'Editar Seccion de Parametro',
        title_ubigeo_new: 'Nuevo Ubigeo',
        title_ubigeo_edit: 'Editar Ubigeo',
        title_tipovia_new: 'Nuevo Tipo de Via',
        title_tipovia_edit: 'Editar Tipo de Via',
        modalidad: 'Modalidad',
        seleccionar:'Seleccionar',
        todos:'Todos',
        ingresodirecto:'Ingreso Directo',
        si:'Si',
        no:'No',
        tiposemestre:'Tipo de Semestre',
        disenio: 'Diseño',
        title_boton_new: 'Nuevo Boton',
        title_boton_edit: 'Editar Boton',
        icono: 'Icono',
        css: 'Css',
        t_btn_alias: 'Este alias se utilizará como ID, debe ser único en el sistema. Se permiten 10 caracteres como máximo.',
        t_btn_css: 'Estilo para el boton',
        title_inscripcion_new: 'Nueva Inscripción',
        title_inscripcion_edit: 'Editar Inscripción',
        title_tipodocumento_new: 'Nuevo Tipo de Documento',
        title_tipodocumento_edit: 'Editar Tipo de Documento',
        buscar_persona: 'Buscar Persona',
        buscar_x_nom_nrodoc: 'Buscar por Nombre o Numero de Documento',
        buscar_seleccionar: 'Seleccionar Persona',
        title_datos_personales: 'Datos Personales',
        title_tipo_documento: 'Tipo de Documento',
        title_tipo_documento_abreviado: 'Tipo de Doc.',
        title_numero_documento: 'Número de Documento',
        title_numero_documento_abreviado: 'Nro. de Doc.',
        hombre: 'Hombre',
        mujer: 'Mujer',
        title_primernombre: 'Primer Nombre',
        title_segundonombre: 'Segundo Nombre',
        title_apellidopaterno: 'Apellido Paterno',
        title_apellidomaterno: 'Apellido Materno',
        title_fechanacimiento: 'Fecha de Nacimiento',
        title_estadocivil: 'Estado Civil',
        title_mediocomunicacion: 'Canales de comunicación',
        title_telefonofijo: 'Teléfono Fijo',
        title_telefonomovil: 'Teléfono Celular',
        title_correopersonal: 'Correo personal',
        title_correocorporativo: 'Correo Corporativo',
        title_lugarrecidencia: 'Lugar de Residencia',
        title_pais: 'País',
        title_ubigeo: 'Ubigeo',
        title_tipovia: 'Típo vía',
        title_tipozona: 'Tipo zona',
        title_direccion: 'Dirección',
        title_lugarnacimiento: 'Lugar de Nacimiento',
        title_estudios: 'Estudios',
        title_tipoinstitucion: 'Tipo de Institución',
        title_institucion: 'Institución',
        title_yearegreso: 'Año de egreso',
        title_inscripcion: 'Inscripción del Postulante',
        title_programa: 'Programa',
        title_semestre: 'Semestre',
        title_sede: 'Sede',
        title_fase: 'Fase',
        title_modalidadadmision: 'Modalidad de admisión',
        title_programaestudio: 'Programa de Estudios',
        title_modalidadestudio: 'Modalidad de estudios',
        title_metodologia: 'Metodología',
        title_segundaopcion: 'Segunda Opción',        
        cerrar_session: 'Cerrar sesión',
        pantalla_full: 'Maximizar pantalla',
        atajo: 'Atajo',
        proyectos: 'Proyectos',
        proyecto_recuentes: 'Proyectos recientes',
        encabezado_fijo: 'Encabezado Fijo',
        menu_fijo: 'Menu Fijo',
        navegacion_fijo: 'Navegación Fijo',
        footer_fijo: 'Footer Fijo',
        contenido_centrado: 'Contenido Centrado',
        menu_derecha: 'Menú a la <b>Derecha</b>',
        menu_arriba: 'Menú <b>Arriba</b>',
        para_daltonicos: 'Para daltónicos',
        reset_options: 'Resetear Opciones',
        reset_theme: 'Resetear apariencia',
        estilos: 'Estilos',
        defecto: 'Defecto',
        oscuro_elegante: 'Oscuro Elegante',
        ultra_claro: 'Ultra Claro',
        anaranjado: 'Anaranjado',
        pixel: 'Pixel',
        trasparente: 'Trasparente',
        celeste: 'Celeste',
        title_usuario_new: 'Nuevo Usuario',
        title_usuario_edit: 'Editar Usuario',        
        title_usuario_reset: 'Cambiar Contraseña',        
        nombreyapellido: 'Nombres y Apellidos',
        apellidoynombre: 'Apellidos y Nombres',
        ultimoacceso: 'Ultimo acceso',
        rol: 'Rol',
        asignarrol: 'Asignar Rol',
        rolasignados: 'Rol Asignados',
        datosacceso:'Datos de Acceso',
        title_rol_new: 'Nuevo Rol',
        title_rol_edit: 'Editar Rol',
        title_tipozona_new: 'Nuevo Tipo de Zona',
        title_tipozona_edit: 'Editar Tipo de Zona',
        title_tipoinstitucion_new: 'Nuevo Tipo de Institución',
        title_tipoinstitucion_edit: 'Editar Tipo de Institución',
        title_tipoprograma_new: 'Nuevo Tipo de Programa',
        title_tipoprograma_edit: 'Editar Tipo de Programa',
        title_rol_access: 'Accesos',
        txt_access: 'El rol <b id="d_rol"></b> tendrá acceso a las siguientes opciones:',
        title_modalidadestudio_new: 'Nueva Modalidad de Estudio',
        title_modalidadestudio_edit: 'Editar Modalidad de Estudio',
        title_gestioninstitucion_new: 'Nueva Gestion de Institución',
        title_gestioninstitucion_edit: 'Editar Gestion de Institución',
        title_institucion_new: 'Nueva Institución',
        title_institucion_edit: 'Editar Institución',
        nro: 'Nro.',
        acciones: 'Acciones',
        nrodocumento_error: 'Numero de Documento Invalido.',        
        title_rol_detail: 'Permisos del Rol',
        search_sensitive: 'Escriba para buscar...',
        detail_rol_buttons: 'Detalle de los permisos del rol.',
        busca_persona: 'Buscar persona...',
        loading: 'Cargando...',
        param_general: 'Parámetros Generales',
        not_exist: 'No existe.',
        edit_param: 'Click para editar',
        title_miembrocontroller_new: 'Nuevo MiembroController',
        title_miembrocontroller_edit: 'Editar MiembroController',
        title_miembro_edit: 'Editar Miembro',
        title_miembro_new: 'Nuevo Miembro',
        tipo_miembro: 'Tipo miembro',
        registrar_diezmo: 'Registrar Diezmo',
        moneda: 'Moneda',
        importe: 'Importe',
        fecha: 'Fecha',
        dni: 'DNI',
        title_etapapersona_new: 'Nueva EtapaPersona',
        title_etapapersona_edit: 'Editar EtapaPersona'
    },/*labels_fin*/
    msn: {/*mensajes ALERT*/
        loginok: 'Ingreso correctamente.',
        loginfail: 'Error con el usuario o contraseña.',
        msn_sys: 'Aviso del sistema:',
        msn_logout: '¿Desea salir: ',
        msn_seguridad_logout: 'Para mayor segurdad cierre el navegador.',
        save_ok: 'Datos se grabaron correctamente.',
        edit_ok: 'Datos se editaron correctamente.',
        delete_ok: 'Registro(s) se eliminó correctamente.',
        you_sure_delete: '¿Está seguro de eliminar el registro?',
        descripcion_exist: 'Descripción ya existe.',
        persona_require: 'Seleccione una Persona',
        mnu: {
            nmenu_exist: 'Descripción de menú ya existe.',
            alias_exist: 'Alias ya existe.',
            ajax_exist: 'Ajax ya existe.'
        },
        adm: {
            fase_exist: 'Fase ya existe.',
            grupo_exist: 'Grupo ya existe.',
            tipoingreso_exist: 'Tipo de Ingreso ya existe.',
            modalidadadmision_exist: 'Modalidad de Admision ya existe.',
            proceso_exist: 'Proceso ya existe.',
            inscripcion_exist: 'Inscripcion ya existe.'        
        }/*adm_fin*/,
        app: {
            semestre_exist: 'Semestre ya existe.',
            filial_exist: 'Filial ya existe.',
            estadocivil_exist: 'Estado Civil ya existe.',
            tiposemestre_exist: 'Tipo de Semestre ya existe.',
            tipoambiente_exist: 'Tipo de Ambiente ya existe.',
            ambiente_exist: 'Ambiente ya existe.',
            tipoestructura_exist: 'Tipo de Estructura ya existe.',        
            estructura_exist: 'Estructura ya existe.',
            pais_exist: 'Pais ya existe.',
            parametro_exist: 'Parametro ya existe.',
            seccionparametro_exist: 'Seccion de Parametro ya existe.',
            ubigeo_exist: 'Ubigeo ya existe.',
            tipovia_exist: 'Tipo de Via ya existe.',
            tipodocumento_exist: 'TipoDocumento ya existe.',
            usuario_exist: 'Usuario ya existe.',
            usuario_persona_exist: 'La persona seleccionada ya existe como Usuario',
            usuario_clave_error: 'La Contraseña ingresada no es valida.',
            rol_exist: 'Rol ya existe.',       
            rol_required: 'Seleccione un Rol.',
            tipozona_exist: 'Tipo de Zona ya existe.',
            documento_exist: 'El Tipo y Numero de documento ya existe.',
            miembrocontroller_exist: 'MiembroController ya existe.',
            miembro_exist: 'Miembro ya existe.'        
        }/*app_fin*/,
        aca: {
            tipoinstitucion_exist: 'Tipo de Institución ya existe.',
            tipoprograma_exist: 'Tipo de Programa ya existe.',
            modalidadestudio_exist: 'Modalidad de Estudio ya existe.',
            gestioninstitucion_exist: 'Gestion de Institución ya existe.',        
            institucion_exist: 'Institución ya existe.'        
        }/*aca_fin*/,
        ig: {
            diezmo_exist: 'Diezmo ya existe.',
            etapapersona_exist: 'EtapaPersona ya existe.'        
        }/*ig_fin*/
    }/*msn_fin*/
};