var language_EN = {
    labels: {/*etiquetas y placeholders*/
        forgot_pass: 'Forgot pass?',
        btn_entrar: 'Entrar',
        copy_right: '&COPY; 2017 -  Perú. Todos los derechos reservados.',
        user: 'Usuario',
        pass: 'Contraseña',
        buscar_menu: 'Buscar menú...',
        m_app: 'Aplicación',
        cambia_pass: 'Cambiar contraseña',
        out: 'Salir',
        search_menu: 'Buscar opcion',
        descripcion: 'Descripción',
        title_nmenu_new: 'Nuevo Menú',
        title_nmenu_edit: 'Editar Menú',
        activo: 'Activo',
        inactivo: 'Inactivo',
        btn_close: 'Cerrar',
        alias: 'Alias',
        ajax: 'Ajax',
        nombre: 'Nombre',
        estado: 'Estado',
        t_alias: 'Este alias se utilizará como prefijo para todos los elementos que serán contenidos en este menú, debe ser único en el sistema. Se permiten 10 caracteres como máximo.',
        t_ajax: `Evento que se ejecutara al dar click en la opción de menú. Ejm: Exe.require({system: 'Boton'},this);`,
        press_enter: 'Escriba y presione [Enter]',
        title_fase_new: 'Nueva Fase',
        title_fase_edit: 'Editar Fase',
        title_grupo_new: 'Nuevo Grupo',
        title_grupo_edit: 'Editar Grupo',
        title_tipoingreso_new: 'Nuevo Tipo de Ingreso',
        title_tipoingreso_edit: 'Editar Tipo de Ingreso',
        title_modalidadadmision_new: 'Nueva Modalidad de Admision',
        title_modalidadadmision_edit: 'Editar Modalidad de Admision',
        title_proceso_new: 'Nuevo Proceso',
        title_proceso_edit: 'Editar Proceso',
        title_semestre_new: 'Nuevo Semestre',
        title_semestre_edit: 'Editar Semestre',
        title_filial_new: 'Nueva Filial',
        title_filial_edit: 'Editar Filial',
        title_estadocivil_new: 'Nuevo Estado Civil',
        title_estadocivil_edit: 'Editar Estado Civil',
        title_tiposemestre_new: 'Nuevo Tipo de Semestre',
        title_tiposemestre_edit: 'Editar Tipo de Semestre',
        title_tipoambiente_new: 'Nuevo Tipo de Ambiente',
        title_tipoambiente_edit: 'Editar Tipo de Ambiente',
        title_ambiente_new: 'Nuevo Ambiente',
        title_ambiente_edit: 'Editar Ambiente',
        title_tipoestructura_new: 'Nuevo Tipo de Estructura',
        title_tipoestructura_edit: 'Editar Tipo de Estructura',
        title_estructura_new: 'Nueva Estructura',
        title_estructura_edit: 'Editar Estructura',
        title_pais_new: 'Nuevo Pais',
        title_pais_edit: 'Editar Pais',
        title_parametro_new: 'Nuevo Parametro',
        title_parametro_edit: 'Editar Parametro',
        title_seccionparametro_new: 'Nueva Seccion de Parametro',
        title_seccionparametro_edit: 'Editar Seccion de Parametro',
        title_ubigeo_new: 'Nuevo Ubigeo',
        title_ubigeo_edit: 'Editar Ubigeo',
        title_tipovia_new: 'Nuevo Tipo de Via',
        title_tipovia_edit: 'Editar Tipo de Via',
        modalidad: 'Modalidad',
        ingresodirecto: 'Ingreso Directo',
        seleccionar:'Seleccionar',
        todos:'Todos',
        ingresodirecto:'Ingreso Directo',
        si:'Si',
        no:'No',
        tiposemestre:'Tipo de Semestre',
        disenio: 'Diseño',
        title_boton_new: 'Nuevo Boton',
        title_boton_edit: 'Editar Boton',
        icono: 'Icono',
        css: 'Css',
        t_btn_alias: 'Este alias se utilizará como ID, debe ser único en el sistema. Se permiten 10 caracteres como máximo.',
        t_btn_css: 'Estilo para el boton',
        title_inscripcion_new: 'Nuevo Inscripcion',
        title_inscripcion_edit: 'Editar Inscripcion',
        title_tipodocumento_new: 'Nuevo TipoDocumento',
        title_tipodocumento_edit: 'Editar TipoDocumento',
        cerrar_session: 'Sign Out',
        pantalla_full: 'Full Screen',
        atajo: 'Shortcut',
        proyectos: 'Projects',
        proyecto_recuentes: 'Recent projects',
        encabezado_fijo: 'Fixed Header',
        menu_fijo: 'Fixed Navigation',
        navegacion_fijo: 'Fixed Ribbon',
        footer_fijo: 'Fixed Footer',
        contenido_centrado: 'Inside <b>.container</b>',
        menu_derecha: 'RTL Support',
        menu_arriba: 'Menu on <b>top</b>',
        para_daltonicos: 'For Colorblind',
        reset_options: 'Reset options',
        reset_theme: 'Reseat appearance',
        estilos: 'Styles',
        defecto: 'Default',
        oscuro_elegante: 'Dark Elegance',
        ultra_claro: 'Ultra Light',
        anaranjado: 'Orange',
        pixel: 'Pixel',
        trasparente: 'Trasparent',
        celeste: 'Light Blue',
        apellidos_nombres: 'Apellidos y Nombres'
    },/*labels_fin*/
    msn: {/*mensajes ALERT*/
        loginok: 'Ingreso correctamente.',
        loginfail: 'Error con el usuario o contraseña.',
        msn_sys: 'Aviso del sistema:',
        msn_logout: '¿Desea salir: ',
        msn_seguridad_logout: 'Para mayor segurdad cierre el navegador.',
        save_ok: 'Datos se grabaron correctamente.',
        edit_ok: 'Datos se editaron correctamente.',
        delete_ok: 'Registro(s) se eliminó correctamente.',
        you_sure_delete: '¿Etá seguro de eliminar el registro?',
        descripcion_exist: 'Descripción ya existe.',
        mnu: {
            nmenu_exist: 'Descripción de menú ya existe.',
            alias_exist: 'Alias ya existe.',
            ajax_exist: 'Ajax ya existe.'
        },
        adm: {
            fase_exist: 'Fase ya existe.',
            grupo_exist: 'Grupo ya existe.',
            tipoingreso_exist: 'Tipo de Ingreso ya existe.',
            modalidadadmision_exist: 'Modalidad de Admision ya existe.',
            proceso_exist: 'Proceso ya existe.',
            inscripcion_exist: 'Inscripcion ya existe.'        
        }/*adm_fin*/,
        app: {
            semestre_exist: 'Semestre ya existe.',
            filial_exist: 'Filial ya existe.',
            estadocivil_exist: 'Estado Civil ya existe.',
            tiposemestre_exist: 'Tipo de Semestre ya existe.',
            tipoambiente_exist: 'Tipo de Ambiente ya existe.',
            ambiente_exist: 'Ambiente ya existe.',
            tipoestructura_exist: 'Tipo de Estructura ya existe.',        
            estructura_exist: 'Estructura ya existe.',
            pais_exist: 'Pais ya existe.',
            parametro_exist: 'Parametro ya existe.',
            seccionparametro_exist: 'Seccion de Parametro ya existe.',
            ubigeo_exist: 'Ubigeo ya existe.',
            tipovia_exist: 'Tipo de Via ya existe.',
            tipodocumento_exist: 'TipoDocumento ya existe.'        
        }/*app_fin*/
    }/*msn_fin*/
};